import type { Locale } from '../i18n/LocaleContext'

export type DocBlock = { heading: string; paragraphs: string[]; bullets?: string[]; code?: string; note?: string }
export type DocPage = { slug: string; group: string; title: string; description: string; blocks: DocBlock[] }

const en: DocPage[] = [
  { slug: 'overview', group: 'Get started', title: 'Growth AI documentation', description: 'Build with Growth AI across browser, terminal and API while keeping identity, memory and access under control.', blocks: [
    { heading: 'A connected AI workspace', paragraphs: ['Growth AI is one product across Growth Chat, Growth CLI and the Growth API. Your approved account determines which models, projects, skills and connections are available on every surface.'], bullets: ['Growth Chat for focused conversations and project folders', 'Growth CLI for development work in the terminal', 'Growth API for controlled product integrations'] },
    { heading: 'Choose your path', paragraphs: ['Start with Growth Chat if you prefer a visual workspace. Use Growth CLI when the work lives in a repository. Integrate through the API when your application needs a stable programmatic interface.'], note: 'Capabilities depend on the account, model and administrator policy. The interface reports unavailable capabilities instead of simulating them.' },
  ]},
  { slug: 'quickstart', group: 'Get started', title: 'Quickstart', description: 'Sign in, choose a model and establish a secure first session.', blocks: [
    { heading: 'Browser', paragraphs: ['Open Growth Chat and sign in with an approved Growth account. New registrations remain pending until an administrator activates them.'], bullets: ['Create a project folder', 'Start a conversation', 'Select the Growth model allowed for your account', 'Review memory and internet controls before sending'] },
    { heading: 'Terminal', paragraphs: ['Install Growth CLI from the approved Growth distribution, then authenticate through the browser. The device code is short-lived and single-use.'], code: 'growth login\ngrowth models\ngrowth chat' },
  ]},
  { slug: 'chat', group: 'Workspaces', title: 'Growth Chat', description: 'Organise conversations and retain useful context without losing control.', blocks: [
    { heading: 'Conversations and folders', paragraphs: ['Conversations belong to your user identity. Folders help separate clients, products or areas of work; moving a conversation never changes its ownership.'], bullets: ['Rename, archive or delete conversations', 'Group related work in custom folders', 'Continue a browser session from its saved history'] },
    { heading: 'Model and capability controls', paragraphs: ['The composer shows the selected model and the capabilities available to it. Internet access, memory and connections are explicit controls and can still be restricted by policy.'] },
  ]},
  { slug: 'cli', group: 'Workspaces', title: 'Growth CLI', description: 'Use Growth AI where your code and terminal workflow already live.', blocks: [
    { heading: 'Sign in securely', paragraphs: ['Run the login command to open a browser confirmation page. After approval, the CLI receives a personal token. The browser never receives or stores an infrastructure master key.'], code: 'growth login\n# Confirm the short-lived code in your browser\ngrowth auth status' },
    { heading: 'Sessions', paragraphs: ['Each session keeps its own conversation context. Resume a saved session for ongoing work or begin a new one when the task should remain isolated.'], note: 'Treat terminal approvals as security boundaries. Review shell, filesystem and connection actions before allowing them.' },
  ]},
  { slug: 'models', group: 'Intelligence', title: 'Models and routing', description: 'Select task depth while Growth handles approved local and remote routes.', blocks: [
    { heading: 'Growth levels', paragraphs: ['Growth low targets fast everyday work. Growth medium balances latency and reasoning. Growth high is intended for demanding engineering and strategic work.'], bullets: ['Availability is account and policy dependent', 'A displayed alias is not a claim that a model is currently loaded', 'Routing health is visible on the public status page'] },
    { heading: 'Data path', paragraphs: ['Requests go through the authenticated Growth gateway. Administrators can permit local or remote inference without exposing internal model ports to the browser or CLI.'] },
  ]},
  { slug: 'skills', group: 'Extend', title: 'Skills', description: 'Reusable instructions and resources for repeatable specialist work.', blocks: [
    { heading: 'What a skill contains', paragraphs: ['A skill can combine scoped instructions with references, templates, scripts and assets. The runtime loads only approved content relevant to the current task.'], bullets: ['Inspect a skill before enabling it', 'Keep credentials outside skill files', 'Treat included scripts as executable code requiring review'] },
    { heading: 'Availability', paragraphs: ['The Skills panel lists only skills installed and permitted in your environment. An empty list means none are available; Growth AI does not invent a catalogue.'] },
  ]},
  { slug: 'plugins', group: 'Extend', title: 'Plugins', description: 'Package approved skills and connections into managed capabilities.', blocks: [
    { heading: 'Managed bundles', paragraphs: ['Plugins group related skills, MCP servers and integration metadata. Installation and updates are administrator-controlled.'], note: 'A plugin does not automatically grant access to external data. Each connection still requires its own authentication and permission.' },
    { heading: 'Review before use', paragraphs: ['Check the publisher, requested permissions, included servers and update policy. Disable a plugin when it is no longer required.'] },
  ]},
  { slug: 'connections', group: 'Extend', title: 'MCP and connections', description: 'Connect approved services without sharing infrastructure credentials.', blocks: [
    { heading: 'Connection lifecycle', paragraphs: ['A connection exposes a narrow set of tools. OAuth or individual credentials should be used when the provider supports them.'], bullets: ['Connect with your own account', 'Review requested scopes', 'Revoke unused access from Growth AI and the provider'] },
    { heading: 'MCP servers', paragraphs: ['MCP can provide tools and resources over configured transports. A configured server is not automatically trusted: Growth applies account policy, approvals and audit controls.'] },
  ]},
  { slug: 'sessions', group: 'Context', title: 'Sessions and context', description: 'Keep work resumable, scoped and understandable.', blocks: [
    { heading: 'Session boundaries', paragraphs: ['A session groups the messages and model responses needed for one line of work. Start a new session when context should not cross projects or clients.'], bullets: ['Use descriptive conversation names', 'Keep confidential projects in separate folders', 'Delete history according to your organisation policy'] },
    { heading: 'Context limits', paragraphs: ['Long sessions can be compacted into a structured summary. Compaction preserves useful decisions but is not a verbatim archive; saved message history remains the source for exact wording.'] },
  ]},
  { slug: 'memory', group: 'Context', title: 'G-Brain and G-Cortex', description: 'Understand how scoped memory and its graph visualisation work together.', blocks: [
    { heading: 'G-Brain memory', paragraphs: ['G-Brain performs scoped recall and capture for approved context associated with your identity and workspace. Retrieval is constrained server-side before context is supplied to a model.'], bullets: ['Personal and project boundaries', 'Explicit memory preferences', 'Auditable retrieval and updates where supported'] },
    { heading: 'G-Cortex visualisation', paragraphs: ['G-Cortex is the graph and visualisation layer for understanding connected knowledge. It is not a separate memory source and does not bypass G-Brain access controls.'], note: 'Memory and internet access are capabilities, not guarantees. Their current availability must be reported by the product.' },
  ]},
  { slug: 'security', group: 'Operate', title: 'Security', description: 'Use Growth AI safely in real development projects.', blocks: [
    { heading: 'Identity and tokens', paragraphs: ['Browser sessions use secure cookies and CSRF protection. CLI access uses personal tokens stored by the client. Passwords, OAuth secrets and raw tokens are never placed in frontend code.'], bullets: ['Use an individual account', 'Rotate a compromised token immediately', 'Never paste master keys into the browser or CLI'] },
    { heading: 'Tools and approvals', paragraphs: ['Shell, filesystem, network and connection access must remain sandboxed and policy-controlled. Review high-impact actions and keep internal services private.'] },
    { heading: 'Prompt injection', paragraphs: ['Treat instructions from web pages, files and connected services as untrusted data. A tool result cannot grant itself additional permissions.'] },
  ]},
  { slug: 'troubleshooting', group: 'Operate', title: 'Troubleshooting', description: 'Resolve common access, connection and model issues.', blocks: [
    { heading: 'Cannot sign in', paragraphs: ['Confirm that the account exists and is active. Pending registrations cannot authenticate. Retry after the rate-limit window and verify that the browser origin is approved.'] },
    { heading: 'Model or capability unavailable', paragraphs: ['Check the model selector and public status page. Availability can differ by account, local server health and remote inference health.'], code: 'growth auth status\ngrowth models' },
    { heading: 'Connection returns an error', paragraphs: ['Reconnect the provider, review its scopes and ask an administrator to verify the server configuration. Do not send credentials through chat.'] },
  ]},
]

const pt: DocPage[] = en.map((page) => ({ ...page }))
Object.assign(pt.find((p) => p.slug === 'overview')!, { title: 'Documentação Growth AI', description: 'Use a Growth AI no browser, terminal e API com identidade, memória e acessos controlados.', blocks: [
  { heading: 'Um espaço de trabalho ligado', paragraphs: ['A Growth AI é um único produto no Growth Chat, Growth CLI e Growth API. A sua conta aprovada determina os modelos, projetos, skills e conexões disponíveis em cada ambiente.'], bullets: ['Growth Chat para conversas e pastas de projeto', 'Growth CLI para desenvolvimento no terminal', 'Growth API para integrações controladas'] },
  { heading: 'Escolha o seu caminho', paragraphs: ['Comece pelo Growth Chat se prefere um espaço visual. Use o Growth CLI quando o trabalho vive num repositório. Integre pela API quando a sua aplicação precisa de uma interface programática estável.'], note: 'As capacidades dependem da conta, modelo e política. A interface indica o que está indisponível, sem o simular.' },
]})

const ptMeta: Record<string, [string, string, string]> = {
  quickstart: ['Primeiros passos', 'Começar', 'Inicie sessão, escolha um modelo e crie uma primeira sessão segura.'], chat: ['Growth Chat', 'Espaços de trabalho', 'Organize conversas e preserve contexto útil sem perder controlo.'], cli: ['Growth CLI', 'Espaços de trabalho', 'Use a Growth AI onde o código e o terminal já vivem.'], models: ['Modelos e encaminhamento', 'Inteligência', 'Escolha a profundidade enquanto a Growth gere rotas locais e remotas aprovadas.'], skills: ['Skills', 'Extensões', 'Instruções e recursos reutilizáveis para trabalho especializado.'], plugins: ['Plugins', 'Extensões', 'Agrupe skills e conexões aprovadas em capacidades geridas.'], connections: ['MCP e conexões', 'Extensões', 'Ligue serviços aprovados sem partilhar credenciais de infraestrutura.'], sessions: ['Sessões e contexto', 'Contexto', 'Mantenha o trabalho retomável, isolado e compreensível.'], memory: ['G-Brain e G-Cortex', 'Contexto', 'Entenda como memória delimitada e a sua visualização em grafo trabalham juntas.'], security: ['Segurança', 'Operação', 'Use a Growth AI com segurança em projetos reais de desenvolvimento.'], troubleshooting: ['Resolução de problemas', 'Operação', 'Resolva problemas comuns de acesso, conexão e modelos.'],
}
pt.forEach((page) => { const meta = ptMeta[page.slug]; if (meta) [page.title, page.group, page.description] = meta })

// Detailed Portuguese sections are intentionally written independently for clarity.
const ptBlocks: Record<string, DocBlock[]> = {
  quickstart: [{ heading: 'Browser', paragraphs: ['Abra o Growth Chat e entre com uma conta Growth aprovada. Novos registos ficam pendentes até ativação por um administrador.'], bullets: ['Crie uma pasta de projeto', 'Inicie uma conversa', 'Selecione um modelo permitido', 'Reveja os controlos de memória e internet'] }, { heading: 'Terminal', paragraphs: ['Instale o Growth CLI pela distribuição aprovada e autentique-se no browser. O código de dispositivo é temporário e de utilização única.'], code: 'growth login\ngrowth models\ngrowth chat' }],
  chat: [{ heading: 'Conversas e pastas', paragraphs: ['As conversas pertencem à sua identidade. As pastas separam clientes, produtos ou áreas; mover uma conversa não altera o proprietário.'], bullets: ['Renomear, arquivar ou eliminar conversas', 'Agrupar trabalho em pastas', 'Retomar histórico guardado'] }, { heading: 'Controlos de modelo', paragraphs: ['O composer mostra o modelo e as capacidades disponíveis. Internet, memória e conexões são explícitas e podem ser limitadas por política.'] }],
  cli: [{ heading: 'Entrada segura', paragraphs: ['O comando de login abre uma confirmação no browser. Depois da aprovação, o CLI recebe um token pessoal; nenhuma master key chega ao browser.'], code: 'growth login\n# Confirme o código temporário no browser\ngrowth auth status' }, { heading: 'Sessões', paragraphs: ['Cada sessão mantém o seu contexto. Retome uma sessão para trabalho contínuo ou crie outra quando a tarefa deva ficar isolada.'], note: 'Reveja ações de shell, ficheiros e conexões antes de as aprovar.' }],
  models: [{ heading: 'Níveis Growth', paragraphs: ['Growth low favorece rapidez, Growth medium equilibra latência e raciocínio, Growth high destina-se a engenharia exigente e decisões estratégicas.'], bullets: ['Disponibilidade depende da conta e política', 'Um alias exposto não confirma que o modelo esteja carregado', 'A saúde do encaminhamento aparece no estado público'] }, { heading: 'Percurso dos dados', paragraphs: ['Os pedidos passam pelo gateway Growth autenticado. Rotas locais e remotas não expõem portas internas ao browser ou CLI.'] }],
  skills: [{ heading: 'Conteúdo de uma skill', paragraphs: ['Uma skill combina instruções delimitadas com referências, templates, scripts e assets. O runtime carrega apenas conteúdo aprovado e relevante.'], bullets: ['Inspecione antes de ativar', 'Mantenha credenciais fora dos ficheiros', 'Reveja scripts como código executável'] }, { heading: 'Disponibilidade', paragraphs: ['O painel mostra apenas skills instaladas e permitidas. Uma lista vazia significa que nenhuma está disponível.'] }],
  plugins: [{ heading: 'Bundles geridos', paragraphs: ['Plugins agrupam skills, servidores MCP e metadados de integração. Instalação e atualização são geridas por administradores.'], note: 'Um plugin não dá acesso automático a dados externos; cada conexão precisa da sua autenticação.' }, { heading: 'Revisão', paragraphs: ['Verifique editor, permissões, servidores e política de atualização. Desative o que deixou de ser necessário.'] }],
  connections: [{ heading: 'Ciclo da conexão', paragraphs: ['Uma conexão expõe ferramentas delimitadas. Use OAuth ou credenciais individuais sempre que possível.'], bullets: ['Ligue a sua conta', 'Reveja os scopes', 'Revogue acessos não usados'] }, { heading: 'Servidores MCP', paragraphs: ['O MCP fornece tools e resources por transports configurados. Um servidor configurado não é automaticamente confiável: continuam a aplicar-se políticas, approvals e auditoria.'] }],
  sessions: [{ heading: 'Limites de sessão', paragraphs: ['Uma sessão agrupa mensagens e respostas de uma linha de trabalho. Crie outra quando o contexto não deva cruzar projetos.'], bullets: ['Use nomes claros', 'Separe projetos confidenciais', 'Elimine histórico conforme a política'] }, { heading: 'Limites de contexto', paragraphs: ['Sessões longas podem ser compactadas num resumo estruturado. O histórico guardado continua a ser a fonte de texto exato.'] }],
  memory: [{ heading: 'Memória G-Brain', paragraphs: ['O G-Brain executa recuperação e captura delimitadas para contexto aprovado associado à identidade e workspace. A recuperação é controlada no servidor antes de chegar ao modelo.'], bullets: ['Limites pessoais e de projeto', 'Preferências explícitas', 'Recuperação auditável quando suportada'] }, { heading: 'Visualização G-Cortex', paragraphs: ['O G-Cortex é a camada de grafo e visualização do conhecimento ligado. Não é uma fonte separada de memória nem contorna os controlos do G-Brain.'], note: 'Memória e internet são capacidades, não garantias; a disponibilidade atual deve ser indicada.' }],
  security: [{ heading: 'Identidade e tokens', paragraphs: ['Sessões browser usam cookies seguros e CSRF. O CLI usa tokens pessoais. Passwords, segredos OAuth e tokens nunca entram no frontend.'], bullets: ['Use conta individual', 'Rode um token comprometido', 'Nunca cole master keys'] }, { heading: 'Ferramentas e approvals', paragraphs: ['Shell, ficheiros, rede e conexões devem permanecer isolados e controlados por política.'] }, { heading: 'Prompt injection', paragraphs: ['Trate instruções vindas da web, ficheiros e serviços como dados não confiáveis. Um resultado não pode ampliar as próprias permissões.'] }],
  troubleshooting: [{ heading: 'Não consigo entrar', paragraphs: ['Confirme que a conta existe e está ativa. Registos pendentes não autenticam. Aguarde o rate limit e confirme a origem aprovada.'] }, { heading: 'Modelo indisponível', paragraphs: ['Consulte o seletor e a página de estado. A disponibilidade varia por conta e saúde das rotas.'], code: 'growth auth status\ngrowth models' }, { heading: 'Erro de conexão', paragraphs: ['Volte a ligar o provider, reveja scopes e peça ao administrador que valide o servidor. Não envie credenciais no chat.'] }],
}
pt.forEach((page) => { if (ptBlocks[page.slug]) page.blocks = ptBlocks[page.slug] })

export const docsByLocale: Record<Locale, DocPage[]> = { en, pt }
